spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  mail:
    host: smtp.163.com
    username: 15095389550@163.com
    password: QNgFp33bK7VXmTy4
    port: 465
    properties:
      from: 15095389550@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: localhost
      port: 6379